spring.datasource.url=jdbc:mysql://localhost:3306/blog_app_apis
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
project.image=images/


aws.s3.bucket-name=my-blogger-images
aws.s3.region=us-east-1
aws.s3.access-key=AKIAT4WPF54XY6B6P6SQ
aws.s3.secret-key=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