server.port=8081

# DB configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.accessTokenExpiryTime=100
jwt.refreshTokenExpiryTime=10
gmail=officialbloggerhub@gmail.com
username.email=officialbloggerhub@gmail.com
password.email=ihhlotkgzwbrplhf
clientId=196704882335-ff56tsuk84qips8baghd10vsq6q7r7hh.apps.googleusercontent.com
jwt.secret=AuDMkgjCwjogTQ8J+lmES/72LcPEN9a+x6bjI1dHo7AfwiQLNWM8wTTSk1TTHtSYfIte334qIKuajXnZF/uRnQ==
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
localhost=https://www.dilnawajtech.in/

logging.level.org.springframework.security=DEBUG
spring.profiles.active=prod
spring.cache.redis.enable-statistics=false
spring.cache.type=redis
spring.main.allow-circular-references=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# CloudWatch Metrics
management.metrics.export.cloudwatch.namespace=BloggerApp
management.metrics.export.cloudwatch.step=1m
management.metrics.export.cloudwatch.enabled=true

# ? AWS 2.x style (matches spring-cloud-aws 2.4.4 + Spring Boot 2.6.6)
cloud.aws.region.static=ap-south-1
cloud.aws.stack.auto=false
cloud.aws.credentials.access-key=AKIAT4WPF54XY6B6P6SQ
cloud.aws.credentials.secret-key=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

# ? SQS
aws.sqs.queue-url=https://sqs.ap-south-1.amazonaws.com/267796213551/my-file-queue
aws.sqs.queue-name=my-file-queue

# Fix Springfox compatibility
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
third.party.api.ai=http://localhost:8082/ai/