spring.datasource.url=jdbc:mysql://blogger-db-2.cb80sai2uksj.eu-north-1.rds.amazonaws.com:3306/blog_app_apis
spring.datasource.username=admin
spring.datasource.password=Blogger123!
spring.jpa.show-sql=true


project.image=/home/ubuntu/blogger/images/